### ISSUE TITLE
(Formidable) Activation Errors 

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#108]
Activation Errors
=========================================================
Name           |   Can't activate
Reporter       |   Elana D.
Submit Date |   8/19/2021
Summary      | When the pre-defined line items add-on is enabled you can not edit or manage any of the items.
Reproduction steps | activate the plugin and below errors display. 

![image](https://user-images.githubusercontent.com/5271694/130078130-2d601464-35e8-4a48-8f05-aa470257a9ea.png)

**Comment by avonville** [comment]
Looks like this is due to formidable and wp forms both being active:
both plugins have this code:
```
define( 'SA_ADDON_INVOICE_SUBMISSIONS_FILE', __FILE__ );
define( 'SA_ADDON_INVOICE_SUBMISSIONS_URL', plugins_url( '', __FILE__ ) );
```

**Comment by elanasparkle** [comment]
Moved to pro repo
