### ISSUE TITLE
Sprout Invoices Add-on - Sprout Billings

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#14]
Not able to have customers manage payment sources

=========================================================
Name           |   sprout-invoices-addon-auto-billing
Reporter       |   Elana D. 
Submit Date |    9/9/2020
Summary      |  When added and activated to the client dashboard Uncaught TypeError: $(...).live is not a function
Reproduction steps |  install sprout-invoices-addon-auto-billing plugin add the tag [sprout_invoices_payments_dashboard] to the client dashboard then the error is in code.  
Platform       | WP 5.5.1 / VPS  / Sprout Invoices Pro 19.9.2.1 / Sprout Invoices 19.9.2 /  sprout-invoices-addon-auto-billing 4.2.6
Browser        | Chrome, Firefox, Safari 

![image](https://user-images.githubusercontent.com/5271694/92644168-eb0ec100-f2b0-11ea-84ca-e03d876a8362.png)

**Comment by elanasparkle** [comment]
Workaround | update the below two pages manually.

sprout-invoices-addon-auto-billing/resources/front-end/js/si-payment-dashboard.js
&
sprout-invoices-addon-auto-billing/resources/front-end/js/si-payments-checkout.js

From .live to .on or .bind

**Comment by elanasparkle** [comment]
Also: 
sprout-invoices-addon-auto-billing/resources/front-end/js/si-payment-dashboard-stripe.js

**Comment by wvcody** [comment]
Added to sprint.

**Comment by elanasparkle** [comment]
Fixed in 19.9.2.3
