### ISSUE TITLE
(SproutBillings) Upgrade FROM Charge API TO Payment Intent API

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#16]
**Summary** (added by @bwmarkle)

In current form, Stripe works but does not work with 3D Secure cards. Update the API to be able to work with 3D Secure cards. To get it to work, we have to update a lot of stuff. Need to upgrade FROM Charge API to Payment Intent API.

* [x] js update from token api to payment method api
    * Fri 7/16 [AV] Hopefully will be completing today.
    * Mon 7/19 [AV] Ran into hiccup...
* [x] server side update charge api to payment intent api
    * [x] charging saved cards with payment intent api
* [x] Testing.
    * Mon 7/19 [AV] Dev work should be done this week, then on to testing.
    * [x] Make sure it does the first change
    * [x] Then a few days later automated billing should be done.

----

Not able to process stripe payments with sprout-invoices-addon-auto-billing

=========================================================
Name | sprout-invoices-addon-auto-billing
Reporter | Elana D.
Submit Date | 9/17/2020
Summary |  When you enable Stripe in Sprout Invoices and then enable the sprout-invoices-addon-auto-billing plugin can't access or process payments. 
Reproduction steps | install sprout-invoices-addon-auto-billing plugin add the tag [sprout_invoices_payments_dashboard] to the client dashboard then enable stripe payment. Payment will not process errors on the site. 
Platform | WP 5.5.1 / VPS / Sprout Invoices Pro 19.9.2.1 / Sprout Invoices 19.9.2 / sprout-invoices-addon-auto-billing 4.2.6
Browser | Chrome, Firefox

![image](https://user-images.githubusercontent.com/5271694/93508125-5fb6b080-f8ec-11ea-89e3-d7d7248f4d17.png)
![image](https://user-images.githubusercontent.com/5271694/93508268-67765500-f8ec-11ea-802c-a264c488c69e.png)
![image](https://user-images.githubusercontent.com/5271694/93508476-73621700-f8ec-11ea-985e-6e14b2749954.png)
![image](https://user-images.githubusercontent.com/5271694/93508895-f6836d00-f8ec-11ea-8f4d-cbcb87898265.png)

Workaround | disable stripe when the addon is enabled or disable the sprout-invoices-addon-auto-billing plugin

**Comment by wvcody** [comment]
Added to sprint.

**Comment by elanasparkle** [comment]
Closing Ticket is in pro.
