### ISSUE TITLE
Sprout Invoices Add-on Attachment Downloads

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#17]
Not able to edit attachments to invoices with add on enabled

=========================================================
Name |sprout-invoices-addon-attachment-downloads 
Reporter | Elana D.
Submit Date | 9/17/2020
Summary | When you enable the sprout-invoices-addon-attachment-downloads plugin can't add attachments  or edit attachments.
Reproduction steps | install sprout-invoices-addon-attachment-downloads plugin add open an invoice an add attachments.
Platform | WP 5.5.1 / VPS / Sprout Invoices Pro 19.9.2.1 / Sprout Invoices 19.9.2 / sprout-invoices-addon-attachment-downloads  1.2
Browser | Chrome, Firefox

![image](https://user-images.githubusercontent.com/5271694/93820043-93664300-fc2a-11ea-8ca8-c0b2b996731a.png)

workaround update the below page manually.

sprout-invoices-addon-attachment-downloads/resources/admin/doc-attachments.js

From .live to .on or .bind

**Comment by dancameron** [comment]
Should retest this since I can't replicate and likely resolved with jQuery updates.

**Comment by elanasparkle** [comment]
Resolved with 19.9.2.2
