### ISSUE TITLE
permission_callback addition for Rest_API_int

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#21]
register_rest_route was called incorrectly in WordPress 5.5+ rest API needs to have permission call back in javascript. 

=========================================================
Name           |   permission_callback rest_api_int 
Reporter       |   Elana D.
Submit Date |    9/28/2020
Summary      |  permission_callback missing from resourcces/admin/settings.js and not called in function register_rest_route() in controllers/admin/settings_api.php 
Reproduction steps | n/a 
Platform       | n/a
PHP Version | n/a
Browser        | n/a 

![image](https://user-images.githubusercontent.com/5271694/94454451-e0dd3580-017f-11eb-8e92-5802ed134959.png)

Workaround | disable WordPress debugging

5.5+ Rest API changes for javascript
https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/#permissions-callback

**Comment by dancameron** [comment]
Fixed with https://github.com/BoldGrid/sprout-invoices/commit/7941130e26cdcde2fab4df3cc67003aa7ea48e48

**Comment by elanasparkle** [comment]
Resolved with 19.9.3.5
