### ISSUE TITLE
Feature Request: More Granular Permissions Controls

### ISSUE THREAD

**Issue by pikurasa** [SproutApps/sprout-invoices#39]
I am trying to add new users to a site who need not read other people's invoices.

Last I checked, it is impossible to have users who could create their own invoices but did not have permission to see others' invoices (even with role editor plugins).

Furthermore, if I remember correctly, the "Editor" role automatically has full permission to see other users' invoices and clients.

It would be nice if the sprouts invoices permissions for invoices, clients, etc. were their own set of permissions so that an admin could assign permissions more granularly.

**Comment by elanasparkle** [comment]
Hello @pikurasa 

I have this in a ticket already for a feature request if you wanted to see that here you can but I'm going to close this one because of the duplicate. 

https://github.com/SproutApps/sprout-invoices/issues/34

**Comment by pikurasa** [comment]
Thanks!

I did check to see if there were any open tickets before submitting, but somehow missed it.

**Comment by elanasparkle** [comment]
> I did check to see if there were any open tickets before submitting, but somehow missed it.

That is ok and what we are here for if you want to keep an eye on it, you can follow #34. Thanks again :)
