### ISSUE TITLE
Sprout Invoices Reporting Export not displaying

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#42]
Not able to export CSV or PDF in reporting functions. None of the sortings is working for any of the reports as well.  

=========================================================
Name           |   Reporting not working in 5.6 
Reporter       |   Elana D.
Submit Date |    12/10/2020
Summary      | not able to export PDF or 
Reproduction steps | go into Sprout Invoices -> reports, and the display is not there, and the sorting is not working either. 

![image](https://user-images.githubusercontent.com/5271694/101828437-8d804f80-3aff-11eb-816b-737577edd9a5.png)

**Comment by sbitpro** [comment]
As of 21 Jan 2021 this is still an issue.  I just received and email from Sprout Invoice Support:

> Thank you for reaching out to support! It looks like you have encountered one of our bugs that we have found with the release of 5.6. I currently have this marked as a high priority and if you wanted to follow the issue you can with the below link. 
> 
> https://github.com/SproutApps/sprout-invoices/issues/42
> 
> ThanksElana D. 

I am hoping that High Priority is soon, This makes Sprout Invoices useless for Taxes if we can not get the reports.

**Comment by elanasparkle** [comment]
Hello @sbitpro 

The jQuery in that section has required us to have to force an update of that code and possibly updating the BootStrap. There is a workaround. If you force jQuery version 2 on your WordPress install, this will work. Unfortunately, I do not have steps on how to accomplish this but will provide the desired result. 

Thanks
Elana D.

**Comment by dancameron** [comment]
Fixed in https://github.com/BoldGrid/sprout-invoices/commit/42fb273764e8663347c5bc5811dccdb266117032

**Comment by elanasparkle** [comment]
Resolved with 19.9.2.4
