### ISSUE TITLE
(SproutPro) (MV) SMS Invoice Notifications 

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#43]
Allow for Customers to send SMS notifications 

=========================================================
Name           |   SMS notifications .
Reporter       |   Elana D.
Submit Date |    12/14/2020
Summary      | SMS alert system to warn customers of unpaid invoices.

**Comment by aldoyh** [comment]
Yes, that would be amazing... I'm trying to integrate with one of the SMS Plugins out there without success!

**Comment by elanasparkle** [comment]
Moving to pro Sprout Invoices repository.
