### ISSUE TITLE
(SproutPro) (MV) Dashboard Wont Display Future Invoices

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#48]
Clients can't see future invoices and redirects when you click on it. 
=========================================================
Name           |   Future / scheduled invoices
Reporter       |   Elana D.
Submit Date |    12/17/2020
Summary      | Scheduled invoices do not allow clients to see them. 
Reproduction steps |

--Step One
- Add a new client
- Add a new invoice, select the client
- In the invoice status, select "Scheduled";
- On the issue date, select 01/02/2021;
- On the due date, select 02/05/2021;
- Save;

--Step Two
- If you are logged in as an administrator, you will be able to view this scheduled invoice (but the error is not here);
- Open an anonymous tab in your browser, go to the client dashboard and view the invoice

- Access the "Client Dashboard" and click on the scheduled invoice (the error is here when clicking the user is taken to an infinite loop and the page is unavailable).

**Comment by dancameron** [comment]
FYI: This was an intentional design choice originally. So that the SI user could create a schedule invoice for the client to see later.

**Comment by elanasparkle** [comment]
Two possible resolutions. Make it not clickable, Make it not Viewable. OR just let the user click into it.

**Comment by elanasparkle** [comment]
Moving to pro Sprout Invoices repository.
