### ISSUE TITLE
Sprout Invoices Status DropDown misplaced. 

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#50]
5.6 WordPress status change from invoice shows dropdown in the top left. 

=========================================================
Name           |   Invoice Status dropdown misplacement 
Reporter       |   Elana D.
Submit Date |    12/18/2020
Summary      | Dropdown always shows in the top left not under the invoice status. 
Reproduction steps | Go to the main invoice screen and try to change the status and the invoice status will show on the top left. 

![image](https://user-images.githubusercontent.com/5271694/102637430-fed58900-4123-11eb-9872-3ffc93c1c79c.png)

**Comment by dancameron** [comment]
Fixed in https://github.com/BoldGrid/sprout-invoices/commit/bfc8ec4fdd58d1aba95ff925f1aa31aa0e584228

**Comment by elanasparkle** [comment]
Issue resolved in 19.9.3.5
