### ISSUE TITLE
Sprout Billings Addon 

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#51]
Not able to set recurring payment duration to zero. 
=========================================================
Name           |   Not able to add recurring payments to be infinite. 
Reporter       |   Elana D.
Submit Date |    12/24/2020
Summary      | We sprout billings are enabled you can not set recurring payments to zero.
Reproduction steps | Setting payments settings to zero will automatically save to one.

**Comment by dancameron** [comment]
FYI: I've told people to use a large number. The cause of this is how some payment providers handle this differently, i.e. some don't allow it at all.

**Comment by elanasparkle** [comment]
Thank you for the information you wouldn't by chance know which ones? I tried to take a few already into large numbers and they didn't entertain the idea.

**Comment by dancameron** [comment]
Hmmm, I'm not sure exactly without testing it out but IIRC something like "9999" should work. If not let me know and I can look into it for you.

**Comment by elanasparkle** [comment]
This is in the 19.9.2.4 release
