### ISSUE TITLE
(SproutPro) (MV) i18n and Currencies (Per Invoice)

### ISSUE THREAD

**Issue by pikurasa** [SproutApps/sprout-invoices#52]
Just now, I was helping someone with Sprouts on their site and they were like "it needs to be in Japanese and billed in Yen". (The majority of invoices are English and USD, just three new ones needed to be JA and Yen. Did not make sense to change things globally.)

And I was like "oh no, I don't think that is possible". Neither seems possible.

We ended up using Paypal's invoicing as a workaround, but I would have rather used Sprouts.

**Comment by elanasparkle** [comment]
Hello @pikurasa, 

Thank you for reaching out. You can set the client currency in the client profile and make sure that you set the client up in each invoice. You can also set up a template as well to specific users if you like as well.

It also looks like Stipe has stopped the direct integration with the YEN currency or JPY. 
https://stripe.com/docs/currencies#presentment-currencies

I'm going to get this labeled and added to a list of bugs to get the YEN / JPY currency conversion updated for Sprout Invoices. 

Thanks
Elana D.

**Comment by pikurasa** [comment]
Thanks for pointing this out.

I wonder if others have trouble discovering this feature?

Reading over the docs from the link you sent, I don't quite see where it says the integration is no longer supported.

I see the following, which seems to indicate support, and I see that yen is a zero-decimal currency (which makes sense).

![Screenshot at 2020-12-28 15:13:39](https://user-images.githubusercontent.com/13454579/103240830-68714680-491f-11eb-94e0-aeb69b7432de.png)

**Comment by elanasparkle** [comment]
Moving to pro Sprout Invoices repository.
