### ISSUE TITLE
Sprout Invoices Notification Records Link. 

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#54]
Viewing Sprout Test Records goes to the wrong link and display si_notification
=========================================================
Name           |   Test Link broken
Reporter       |   Elana D.
Submit Date |    1/4/2020
Summary      | Can't get to SI_records from the settings page. 
Reproduction steps | go to Sprout Invoices -> notification settings -> send a test notification, then the link will appear. Click the link, and it goes to 

wp-admin/tools.php?page=sprout-apps%2Fsi_records

Which doesn't exist; It should be 

wp-admin/tools.php?page=si_records&sa_record_type=20&si_record_purge_nonce&paged=1

![image](https://user-images.githubusercontent.com/5271694/103587033-5a3da000-4eb4-11eb-85af-9942c390fbdd.png)

**Comment by dancameron** [comment]
FYI: Record types IIRC have different IDs per site (or can) so they're linked to the main dash. 🤷‍♂️

**Comment by elanasparkle** [comment]
Fixed in 19.9.4.1 and 19.9.4 of Sprout Invoices.
