### ISSUE TITLE
Sprout Invoices WP E-Signature integration

### ISSUE THREAD

**Issue by joe9663** [SproutApps/sprout-invoices#56]
### Description
WP E-Signature's Sprout invoice add-on adds a legally binding document to the Sprout invoice workflow. Because they are an electronic document signing platform, they have to provide access to the customer's records which means sending them a PDF copy of their signed E-Signature document. This works perfectly in other workflows, but when combined with a Sprout workflow, the E-Signature confirmation email is getting disabled. This email is a requirement that must be included in any workflow with WP E-Signature the issue needs to be resolved to remain compliant.

The reason the confirmation email is getting disabled is because after signing the document, Sprout is redirecting back to the invoice with **esig_document_complete** action hook.

### Solution
Change the workflow so that Sprout redirects back to the invoices with one of these action hooks instead: **esig_email_sent** or **esig_after_sad_process_done**.

This will make sure the E-Signature confirmation email sends to provide the signer the PDF that they need from WP E-Signature and keep the rest of the Sprout workflow working.

**Comment by elanasparkle** [comment]
Fixed in 19.9.4.1 and 19.9.4 of Sprout Invoices.
