### ISSUE TITLE
(SproutPro) (MV) Multiple Payment Processors Selection

### ISSUE THREAD

**Issue by harryjackson1221** [SproutApps/sprout-invoices#57]
Currently, you can only select one payment processor at a time in Sprout Invoices:
[https://docs.sproutinvoices.com/article/10-payment-settings](https://docs.sproutinvoices.com/article/10-payment-settings)

This feature request is to allow for different configurations of multiple processors, such as using Stripe and PayPal in conjunction, as this is becoming more and more common for other products and services. 

In the future, options for other non traditional processors such as Google, Apple or Amazon Pay could be introduced alongside traditional credit card processing as well.

**Comment by elanasparkle** [comment]
Its the top block of processors that need to be looked at.

**Comment by elanasparkle** [comment]
Moving to pro Sprout Invoices repository.
