### ISSUE TITLE
Beacon Not Working

### ISSUE THREAD

**Issue by dancameron** [SproutApps/sprout-invoices#58]
<img width="162" alt="Screen Shot 2021-01-25 at 10 42 02 AM" src="https://user-images.githubusercontent.com/1413460/105750792-02fe7e80-5efa-11eb-9a97-a8d7c828a314.png">
<img width="1346" alt="Screen Shot 2021-01-25 at 10 42 07 AM" src="https://user-images.githubusercontent.com/1413460/105750793-03971500-5efa-11eb-8e66-3f2767069659.png">

**Comment by dancameron** [comment]
https://github.com/BoldGrid/sprout-invoices/commit/b6d40407a15de14332953b6340d2a22d09b4a13c

**Comment by dancameron** [comment]
I guess this should be reviewed first.

**Comment by elanasparkle** [comment]
Resolved in 19.9.2.4
