### ISSUE TITLE
Stripe Checkout needs upgrade

### ISSUE THREAD

**Issue by pikurasa** [SproutApps/sprout-invoices#6]
If you go into "test" mode and make a test payment on an invoice using stripe it shows the notification "You're using an older version of Stripe Checkout."

It links to https://stripe.com/docs/payments/checkout/migration and has an email address of plugins@stripe.com for additional help.

**Comment by elanasparkle** [comment]
This is apart of our current sprint and can be seen here. 

https://github.com/SproutApps/sprout-invoices/issues/16
