### ISSUE TITLE
(Sprout) Can not add a line item with a null value

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#65]
No line items are saved with a blank description in the form. This is not a required field when setting up a line item but you can set up the payment and percentage without a description then it disappears. 

![image](https://user-images.githubusercontent.com/5271694/108898140-d915a600-75e4-11eb-969d-5be6d7666b08.png)

**Comment by avonville** [comment]
Released with 19.9.8/19.8.8.1 closing
