### ISSUE TITLE
Receipt not Generated after Payment | Fatal Error

### ISSUE THREAD

**Issue by pikurasa** [SproutApps/sprout-invoices#7]
For about 2 months, I have been trying to report this error to SI support no avail. I have a multi-site license -- the top tier of license you can get for SI.

Context:
* I have a multisite WP (the a.example.com subdomain kind)

Issue: When a customer makes a payment for the invoice, they see a "fatal error". The payment (thankfully) is made, but every customer who has done this sends me a message asking what happened. It really unnerves the customers during the payment process.

I went into debug mode yesterday, and this is what I see when I make a (test) payment:

```
Notice: Undefined variable: history in /srv/data/web/vhosts/mapflc.com/htdocs/wp-content/plugins/sprout-invoices-pro/template-tags/invoices.php on line 1010

Warning: array_diff(): Expected parameter 1 to be an array, null given in /srv/data/web/vhosts/mapflc.com/htdocs/wp-content/plugins/sprout-invoices-pro/bundles/sprout-invoices-addon-payment-terms/inc/Payment_Terms.php on line 95

Warning: asort() expects parameter 1 to be array, null given in /srv/data/web/vhosts/mapflc.com/htdocs/wp-content/plugins/sprout-invoices-pro/template-tags/invoices.php on line 1012

Warning: Invalid argument supplied for foreach() in /srv/data/web/vhosts/mapflc.com/htdocs/wp-content/plugins/sprout-invoices-pro/template-tags/invoices.php on line 1014

Fatal error: Uncaught Error: Call to a member function get_client_id() on string in /srv/data/web/vhosts/mapflc.com/htdocs/wp-content/plugins/sprout-invoices-pro/bundles/sprout-invoices-addon-woocommerce/template-tags/vat.php:6 Stack trace: #0 /srv/data/web/vhosts/mapflc.com/htdocs/wp-content/plugins/sprout-invoices-pro/bundles/sprout-invoices-addon-woocommerce/inc/Woo_Tools.php(54): si_wc_get_client_vat() #1 /srv/data/web/vhosts/mapflc.com/htdocs/wp-includes/class-wp-hook.php(287): Woo_Tools::add_vat_number_to_doc('') #2 /srv/data/web/vhosts/mapflc.com/htdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 /srv/data/web/vhosts/mapflc.com/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #4 /srv/data/web/vhosts/mapflc.com/htdocs/wp-content/plugins/sprout-invoices-pro/views/templates/theme/default/invoice/invoice.php(90): do_action('si_document_vca...') #5 /srv/data/web/vhosts/mapflc.com/htdocs/wp-includes/template-loader.php(106): include('/srv/data/web/v...') #6 /srv/data/web/vhosts in /srv/data/web/vhosts/mapflc.com/htdocs/wp-content/plugins/sprout-invoices-pro/bundles/sprout-invoices-addon-woocommerce/template-tags/vat.php on line 6
```

Expected Result:
* I expect a receipt to be generated. Customers are greeted by the fatal error screen and the receipt that is emailed to the customer is a PDF of the website's "404 page not found"

Other:
* No such issue with estimates.

I also sent a detailed report to support for SI, but since the response time is so delayed and since the person I was talking to switched in the middle of us trying to figure out what is wrong, I am putting it here.

**Comment by elanasparkle** [comment]
Hello Devin, 

Sorry, I didn't see this before but I remember us solving this on the ticket we were working on. 

Thanks
Elana D.
