### ISSUE TITLE
Zapier Line items not Populating

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#85]
Not able to add line items to Zapier in invoice creation. 
=========================================================
Name           |   Not able to add line items for invoice creation. 
Reporter       |   Elana D.
Submit Date |   5/6/2021
Summary      | When you add a Zap to trigger an invoice creation, the line items are not populating.

**Comment by avonville** [comment]
* [x] How is the form set up on Zap?
* [x] What exactly changed? Who changed it? When?
json_encode with no arguments creates an object not array.
* [x] Was this working or is the customer setting this up for the first?
no

**Comment by bwmarkle** [comment]
[AV] Currently working on solution. Can add 1 line item, have user testing beta version... Issue is that Zapier created a new builder.

[HJ] Ours is in a beta. Can we publish it in the Zapier directory @bwmarkle 
* [AV] If public, it means everyone can use it. Is that ok?
* [HJ] The code would be in the pro plugin, they would need api key to use it.

**Comment by avonville** [comment]
**Updated**

Multiple line items can be added now. Updated the Zapier integration so it is live to anyone who has access. Looking into making the App public.
