### ISSUE TITLE
(SproutPro) Variable Products in WooCommerce 

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#87]
Not able to add variable products in the line item dropdown.
=========================================================
Name           |   variable products in the line item dropdown.
Reporter       |   Elana D.
Submit Date |   7/14/2021
Summary      | Unable to search or find variable products in the WooCommerce dropdown in the line item sections in Sprout Invoices.

**Comment by dancameron** [comment]
At the moment we have categories grouping the products, if we add variables I recommend:

1. Removing categories for grouping products, and use products for grouping if variables are present. 
2. Keep the current category grouping, and each variation will be its own option.  [dev note](https://stackoverflow.com/a/49348603/1101471)

I'd recommend option 2, so it doesn't disrupt anyone that relies on the categories and avoids possible conflicts with mixing products with and without variations.

**Comment by elanasparkle** [comment]
Moving to pro Sprout Invoices repository.
