### ISSUE TITLE
(HelpScoutDesk) Add facade to lazy load Help Scout Desk Beacon

### ISSUE THREAD

**Issue by harryjackson1221** [SproutApps/sprout-invoices#91]
https://web.dev/third-party-facades/

To increase performance of websites using the product, lazy loading the chat bubble with a facade will help decrease page load speed on average about a third of a second. From Lighthouse:

![image](https://user-images.githubusercontent.com/29436971/118177601-e6cb1280-b400-11eb-8a98-20aa3e0f0559.png)

From PageSpeed Insights:
![image](https://user-images.githubusercontent.com/29436971/118177785-27c32700-b401-11eb-8fea-293d680b02fe.png)

**Comment by elanasparkle** [comment]
Moving to pro Sprout Invoices repository.
