### ISSUE TITLE
(HelpScout) (MV) Feature Request: Link to Customer Record

### ISSUE THREAD

**Issue by tobeyadr** [SproutApps/sprout-invoices#93]
Hi! Can you please add the following details to the top of EDD card in helpscout? It would make my life that much easier.

![image](https://user-images.githubusercontent.com/24380643/112669162-c4237100-8e35-11eb-8797-4884c8daf7f2.png)

- Customer ID with a link to the customer record
- The number of Successful payments (status Paid)
- The total customer value
- The number of active subs (if EDD recurring is active)

Thanks in advance!

**Comment by elanasparkle** [comment]
Moving to our pro repository to help with visibility.
